"""Character CUSTOMISATION (STATUS item 4): many distinct characters from the two base bodies.

Imported by base_humans.py after chr_lib (runs inside Blender). It adds, on the live MPFB human, before the export bake:
  * face + body morph targets named 'cust_<slider>_neg' / 'cust_<slider>_pos' from MPFB's CC0 MakeHuman targets
    (symmetric l-/r- pairs summed into one morph; body 'muscle' / 'weight' are MakeHuman MACRO deltas computed with
    MPFB's own macro interpolation), interpolated onto every part (brows, lashes, eyes, teeth, tongue, hair, beards)
    through the parts' mhclo vertex correspondence, exactly like MPFB does for the ARKit / viseme keys;
  * swappable parts: alternate CC0 eyebrows / eyelashes / hair styles and procedural beards (scripts/hair_gen.py),
    skinned to the same rts_human skeleton and carrying the same face + cust morph names; exported to a separate
    out/parts_<kind>.glb so the base GLB stays a clean default character;
  * material variants (KHR_materials_variants, written by glb_post.py): skin tones, eye colours, hair colours;
  * per-morph skeleton refit offsets (how each cust morph moves the joints, from MPFB's own rig strategies), so an
    engine (and the viewer) can refit the skeleton for extreme shapes;
  * proportion variants (height / build need a skeleton refit, so they are separate builds, see VARIANT_PRESETS).
"""
import os, json, copy, time
import numpy as np
from chr_lib import *
from bl_ext.user_default.mpfb.services import ClothesService
from bl_ext.user_default.mpfb.entities.clothes.mhclo import Mhclo
from bl_ext.user_default.mpfb.entities.rig import Rig

CUST = "cust_"
MPFB_TARGETS = LocationService.get_mpfb_data("targets")
PARTS_TEX = os.path.join(TEX, "parts")          # generated by scripts/part_tex.py (neutral hair, eye colours)
NBODY = 13380                                   # MakeHuman body vertices (the rest of the basemesh is helpers)

# ------------------------------------------------------------------------------------------------------------------
# Slider table. id, group, "neg label / pos label", negative side, positive side, randomise range (0..1).
# A side is a MakeHuman target name, 'LR:<name>' (l-<name> + r-<name> summed = symmetric), a list of those, a dict
# of MakeHuman macro values ({'muscle': 1.0}: delta from the preset's macro to that value), or None (one-sided).
# Morphs: cust_<id>_neg and cust_<id>_pos. Engine slider s in [-1, 1]: neg weight = max(0, -s), pos = max(0, s).
# The sliders are offsets FROM the base preset (the preset already uses some of these targets).
FACE_SLIDERS = [
    ("nose_width",       "Nose",  "narrow / wide",          "nose-scale-horiz-decr",   "nose-scale-horiz-incr",   0.7),
    ("nose_length",      "Nose",  "short / long",           "nose-scale-vert-decr",    "nose-scale-vert-incr",    0.6),
    ("nose_projection",  "Nose",  "flat / prominent",       "nose-scale-depth-decr",   "nose-scale-depth-incr",   0.6),
    ("nose_bridge",      "Nose",  "smooth / humped",        "nose-hump-decr",          "nose-hump-incr",          0.7),
    ("nose_curve",       "Nose",  "snub / hooked",          "nose-curve-concave",      "nose-curve-convex",       0.6),
    ("nose_tip",         "Nose",  "tip down / tip up",      "nose-point-down",         "nose-point-up",           0.6),
    ("nose_tip_width",   "Nose",  "fine / bulbous",         "nose-point-width-decr",   "nose-point-width-incr",   0.7),
    ("nose_nostrils",    "Nose",  "narrow / flared",        "nose-nostrils-width-decr", "nose-nostrils-width-incr", 0.7),
    ("mouth_width",      "Mouth", "narrow / wide",          "mouth-scale-horiz-decr",  "mouth-scale-horiz-incr",  0.6),
    ("lip_upper",        "Mouth", "thin / full upper lip",  "mouth-upperlip-volume-decr", "mouth-upperlip-volume-incr", 0.7),
    ("lip_lower",        "Mouth", "thin / full lower lip",  "mouth-lowerlip-volume-decr", "mouth-lowerlip-volume-incr", 0.7),
    ("mouth_cupidsbow",  "Mouth", "flat / defined bow",     "mouth-cupidsbow-decr",    "mouth-cupidsbow-incr",    0.7),
    ("mouth_corners",    "Mouth", "down / up",              "mouth-angles-down",       "mouth-angles-up",         0.5),
    ("mouth_height",     "Mouth", "low / high",             "mouth-trans-down",        "mouth-trans-up",          0.5),
    ("eyes_size",        "Eyes",  "small / large",          "LR:eye-scale-decr",       "LR:eye-scale-incr",       0.6),
    ("eyes_spacing",     "Eyes",  "close / wide",           "LR:eye-trans-in",         "LR:eye-trans-out",        0.6),
    ("eyes_height",      "Eyes",  "low / high",             "LR:eye-trans-down",       "LR:eye-trans-up",         0.5),
    ("eyes_depth",       "Eyes",  "deep-set / prominent",   "LR:eye-push1-in",         "LR:eye-push1-out",        0.6),
    ("eyes_tilt",        "Eyes",  "outer corners down / up", "LR:eye-corner2-down",    "LR:eye-corner2-up",       0.7),
    ("eyes_bags",        "Eyes",  "smooth / baggy",         "LR:eye-bag-decr",         "LR:eye-bag-incr",         0.6),
    ("brows_height",     "Brows", "low / high",             "eyebrows-trans-down",     "eyebrows-trans-up",       0.6),
    ("brows_angle",      "Brows", "stern / raised outer",   "eyebrows-angle-down",     "eyebrows-angle-up",       0.6),
    ("brows_ridge",      "Brows", "flat / heavy ridge",     "eyebrows-trans-backward", "eyebrows-trans-forward",  0.6),
    ("jaw_width",        "Jaw & chin", "narrow / wide jaw", "chin-bones-decr",         "chin-bones-incr",         0.7),
    ("jaw_length",       "Jaw & chin", "short / long jaw",  "chin-jaw-drop-decr",      "chin-jaw-drop-incr",      0.6),
    ("chin_height",      "Jaw & chin", "short / tall chin", "chin-height-decr",        "chin-height-incr",        0.6),
    ("chin_width",       "Jaw & chin", "narrow / wide chin", "chin-width-decr",        "chin-width-incr",         0.7),
    ("chin_prominence",  "Jaw & chin", "receding / jutting", "chin-prominent-decr",    "chin-prominent-incr",     0.7),
    ("chin_cleft",       "Jaw & chin", "- / cleft",         None,                      "chin-cleft-incr",         0.8),
    ("cheekbones",       "Cheeks", "soft / high",           "LR:cheek-bones-decr",     "LR:cheek-bones-incr",     0.7),
    ("cheeks_volume",    "Cheeks", "hollow / full",         "LR:cheek-volume-decr",    "LR:cheek-volume-incr",    0.6),
    ("ears_size",        "Ears",  "small / large",          "LR:ear-scale-decr",       "LR:ear-scale-incr",       0.6),
    ("ears_protrusion",  "Ears",  "flat / protruding",      "LR:ear-wing-decr",        "LR:ear-wing-incr",        0.6),
    ("ears_pointed",     "Ears",  "- / pointed (elf)",      None,                      "LR:ear-shape-pointed",    0.0),
    ("forehead_height",  "Head",  "low / high forehead",    "forehead-scale-vert-decr", "forehead-scale-vert-incr", 0.6),
    ("head_width",       "Head",  "narrow / wide",          "head-scale-horiz-decr",   "head-scale-horiz-incr",   0.5),
    ("face_age",         "Head",  "younger / older",        "head-age-decr",           "head-age-incr",           0.7),
    ("face_weight",      "Head",  "gaunt / round",          "head-fat-decr",           "head-fat-incr",           0.6),
]
BODY_SLIDERS = [
    ("body_muscle",      "Body",  "soft / muscular",        {"muscle": 0.3},           {"muscle": 1.0},           0.6),
    ("body_weight",      "Body",  "thin / heavy",           {"weight": 0.15},          {"weight": 1.0},           0.6),
    ("body_shoulders",   "Body",  "narrow / broad",         "measure-shoulder-dist-decr", "measure-shoulder-dist-incr", 0.6),
    ("body_chest",       "Body",  "slim / barrel chest",    "measure-bust-circ-decr",  "measure-bust-circ-incr",  0.5),
    ("body_waist",       "Body",  "narrow / wide waist",    "measure-waist-circ-decr", "measure-waist-circ-incr", 0.5),
    ("body_belly",       "Body",  "flat / pot belly",       "stomach-pregnant-decr",   "stomach-pregnant-incr",   0.4),
    ("body_hips",        "Body",  "narrow / wide hips",     "measure-hips-circ-decr",  "measure-hips-circ-incr",  0.5),
    ("body_arms",        "Body",  "thin / thick arms",      "measure-upperarm-circ-decr", "measure-upperarm-circ-incr", 0.5),
    ("body_legs",        "Body",  "thin / thick thighs",    "measure-thigh-circ-decr", "measure-thigh-circ-incr", 0.5),
    ("neck_thickness",   "Body",  "thin / thick neck",      "measure-neck-circ-decr",  "measure-neck-circ-incr",  0.5),
]
BODY_SLIDERS_KIND = {"female": [("body_bust", "Body", "small / large bust", {"cupsize": 0.15}, {"cupsize": 0.9}, 0.5)]}


def sliders_for(kind):
    base = PRESETS[kind].get("tex_kind", kind)
    return FACE_SLIDERS + BODY_SLIDERS + BODY_SLIDERS_KIND.get(base, [])


def morph_names(kind):
    out = []
    for sid, grp, lab, neg, pos, rnd in sliders_for(kind):
        if neg is not None:
            out.append(CUST + sid + "_neg")
        out.append(CUST + sid + "_pos")
    return out


# ------------------------------------------------------------------------------------------------------------------
# Swappable parts. Hair: CC0 MakeHuman styles + the project's procedural grooms; beards: procedural (hair_gen.py);
# brows / lashes: every CC0 style. Defaults stay in the base GLB; alternates go to out/parts_<kind>.glb.
HAIR_ALTS = {"male": ["rts_braid", "ponytail01", "long01", "short02", "bob02"],
             "female": ["rts_crop", "ponytail01", "long01", "bob02", "short02"]}
# rts_stubble = the skin-hugging stubble shell (alpha-blended); the card beards also get that shell with a dense
# 'shadow' texture as a second primitive (merge_beard_shadows), so the skin never shows between the cards
BEARDS = {"male": ["rts_stubble", "rts_beard_short", "rts_beard_full"], "female": []}
STUBBLE = "rts_stubble"
# hair colours: sRGB 'strand' colour as used by hair_tex.py (atlas = strand luminance x colour x 1.5)
HAIR_COLOURS = [("black", (0.055, 0.045, 0.04)), ("dark brown", (0.17, 0.11, 0.07)), ("chestnut", (0.20, 0.11, 0.07)),
                ("brown", (0.30, 0.18, 0.10)), ("auburn", (0.34, 0.13, 0.065)), ("ginger", (0.50, 0.22, 0.09)),
                ("dirty blond", (0.44, 0.34, 0.20)), ("blond", (0.60, 0.48, 0.30)), ("grey", (0.40, 0.39, 0.38)),
                ("white", (0.62, 0.61, 0.58))]
EYE_COLOURS = ["brownlight", "brown", "green", "bluegreen", "blue", "lightblue", "deepblue", "grey", "ice"]
# skin tones: CC0 MakeHuman skins (same UV), mixed in linear space, then the base pipeline's AO / grade / scalp tint
# (scripts/skin_variants.py). 'tint' variants are a baseColorFactor on the default albedo (fantasy tones).
# (tone, [(CC0 skin, weight)], saturation multiplier: the CC0 dark albedo is quite red, mixed tones are desaturated)
SKIN_TONES = {
    "male": [("fair", None, 1.0), ("tan", [("young_caucasian_male", 0.6), ("young_african_male", 0.4)], 0.9),
             ("brown", [("young_caucasian_male", 0.3), ("young_african_male", 0.7)], 0.8),
             ("dark", [("young_african_male", 1.0)], 0.92), ("weathered", [("old_caucasian_male", 1.0)], 1.0)],
    "female": [("fair", None, 1.0), ("tan", [("young_caucasian_female", 0.6), ("young_african_female", 0.4)], 0.9),
               ("brown", [("young_caucasian_female", 0.3), ("young_african_female", 0.7)], 0.8),
               ("dark", [("young_african_female", 1.0)], 0.92), ("weathered", [("old_caucasian_female", 1.0)], 1.0)],
}
SKIN_TINTS = [("orc green", (0.42, 0.62, 0.27)), ("ashen", (0.5, 0.56, 0.66))]

# ------------------------------------------------------------------------------------------------------------------
# Proportion variants: stature / limb proportions change the skeleton, so they are separate builds (MPFB refits the
# rts_human joints to the new body automatically). Same textures (tex_kind), same parts, same morph names.
VARIANT_PRESETS = {
    "male_stocky": dict(base="male", stature=1.47,
                        phenotype=dict(muscle=1.0, weight=0.82, proportions=0.35),
                        add_targets={"upperlegs-height-decr": 0.7, "lowerlegs-height-decr": 0.5,
                                     "measure-upperarm-length-decr": 0.35, "measure-lowerarm-length-decr": 0.3,
                                     "torso-scale-horiz-incr": 0.35, "measure-neck-height-decr": 0.5,
                                     "head-scale-horiz-incr": 0.25, "nose-scale-horiz-incr": 0.4,
                                     "nose-point-width-incr": 0.5, "stomach-pregnant-incr": 0.25,
                                     "measure-hips-circ-incr": 0.3}),
    "male_slim": dict(base="male", stature=1.95,
                      phenotype=dict(muscle=0.62, weight=0.3),
                      add_targets={"upperlegs-height-incr": 0.35, "measure-neck-height-incr": 0.4,
                                   "torso-vshape-incr": -0.25, "head-fat-decr": 0.2, "head-scale-horiz-decr": 0.25,
                                   "chin-width-decr": 0.3, "l-cheek-bones-incr": 0.2, "r-cheek-bones-incr": 0.2}),
    "female_slim": dict(base="female", stature=1.80,
                        phenotype=dict(muscle=0.6, weight=0.3),
                        add_targets={"upperlegs-height-incr": 0.35, "measure-neck-height-incr": 0.4,
                                     "head-scale-horiz-decr": 0.2, "chin-width-decr": 0.2}),
}


def _variant_preset(name, spec):
    p = copy.deepcopy(PRESETS[spec["base"]])
    p["tex_kind"] = spec["base"]
    p["stature"] = spec["stature"]
    p["phenotype"].update(spec["phenotype"])
    for t, v in spec["add_targets"].items():
        if v < 0:      # negative = remove / reduce a preset target
            p["targets"][t] = max(0.0, p["targets"].get(t, 0.0) + v)
        else:
            p["targets"][t] = p["targets"].get(t, 0.0) + v
    p["targets"] = {k: v for k, v in p["targets"].items() if v > 0}
    return p


for _n, _s in VARIANT_PRESETS.items():
    PRESETS[_n] = _variant_preset(_n, _s)


# ------------------------------------------------------------------------------------------------------------------
def _key_co(obj, key):
    n = len(obj.data.vertices)
    a = np.empty(n * 3); key.data.foreach_get("co", a)
    return a.reshape(-1, 3)


def _target_delta(bm, basis, name):
    path = TargetService.target_full_path(name)
    assert path and os.path.basename(path).startswith(name + ".target"), (name, path)
    k = TargetService.load_target(bm, path, weight=0.0, name="__tmp_cust")
    d = _key_co(bm, k) - basis
    bm.shape_key_remove(k)
    return d


def _macro_delta(bm, basis, changes):
    """Mesh delta (basemesh local, all vertices incl. helpers) of changing MakeHuman macros from the preset's values
    to `changes`, using MPFB's own macro-target interpolation (the same stack reapply_macro_details would load)."""
    info = TargetService.get_macro_info_dict_from_basemesh(bm)
    mod = copy.deepcopy(info); mod.update(changes)
    a = {t: w for t, w in TargetService.calculate_target_stack_from_macro_info_dict(info, cutoff=0.0)}
    b = {t: w for t, w in TargetService.calculate_target_stack_from_macro_info_dict(mod, cutoff=0.0)}
    D = np.zeros_like(basis)
    for t in set(a) | set(b):
        dw = b.get(t, 0.0) - a.get(t, 0.0)
        if abs(dw) < 1e-7:
            continue
        path = os.path.join(MPFB_TARGETS, t + ".target.gz")
        k = TargetService.load_target(bm, path, weight=0.0, name="__tmp_macro")
        D += dw * (_key_co(bm, k) - basis)
        bm.shape_key_remove(k)
    return D


def _expand(side):
    return ["l-" + side[3:], "r-" + side[3:]] if side.startswith("LR:") else [side]


def slider_deltas(bm, basis, kind, neg, pos):
    """(neg delta, pos delta, preset modifier value). Target sliders map s = +-1 to MakeHuman's full modifier range
    RELATIVE TO THE PRESET: if the preset already uses the pair at modifier value m0 (incr weight a = max(m0, 0),
    decr weight b = max(-m0, 0)), then pos = (1 - a) * incr - b * decr and neg = (1 - b) * decr - a * incr, so the
    base + any slider value stays inside MakeHuman's authored [-1, 1] range (no double-dipping)."""
    if isinstance(pos, dict):
        return (_macro_delta(bm, basis, neg) if neg else None), _macro_delta(bm, basis, pos), None
    pv = PRESETS[kind]["targets"]
    P = _expand(pos); N = _expand(neg) if neg else [None] * len(P)
    Dp = np.zeros_like(basis); Dn = np.zeros_like(basis) if neg else None
    m0s = []
    for n, p in zip(N, P):
        dp = _target_delta(bm, basis, p)
        dn = _target_delta(bm, basis, n) if n else 0.0
        m0 = pv.get(p, 0.0) - (pv.get(n, 0.0) if n else 0.0)
        a, b = max(m0, 0.0), max(-m0, 0.0)
        Dp += (1 - a) * dp - b * dn
        if n:
            Dn += (1 - b) * dn - a * dp
        m0s.append(m0)
    return Dn, Dp, round(float(np.mean(m0s)), 3)


PRESET_MOD = {}


def add_cust_keys(bm, kind):
    """Adds every cust_* morph to the live basemesh as a shape key (value 0). Returns {morph: stats}."""
    kb = bm.data.shape_keys.key_blocks
    basis = _key_co(bm, kb["Basis"])
    stats = {}
    t0 = time.time()
    for sid, grp, lab, neg, pos, rnd in sliders_for(kind):
        Dn, Dp, m0 = slider_deltas(bm, basis, kind, neg, pos)
        PRESET_MOD[sid] = m0
        for suffix, D in (("_neg", Dn), ("_pos", Dp)):
            if D is None:
                continue
            name = CUST + sid + suffix
            sk = bm.shape_key_add(name=name, from_mix=False)
            sk.data.foreach_set("co", (basis + D).ravel())
            sk.value = 0.0
            mag = np.linalg.norm(D[:NBODY], axis=1)
            stats[name] = dict(verts=int((mag > 1e-6).sum()), max_mm=round(float(mag.max()) * 1000, 2),
                               feet_mm=round(float(D[:NBODY][basis[:NBODY, 2] < basis[:NBODY, 2].min() + 0.02, 2].mean()) * 1000, 2))
    log("cust keys: %d morphs in %.1fs" % (len(stats), time.time() - t0))
    return stats


def interpolate_keys_to_parts(rig, bm, names, min_shift=1e-4):
    """Barycentric mhclo interpolation of basemesh shape keys onto every child part (brows, lashes, eyes, teeth, tongue,
    hair, beards), as FaceService.interpolate_targets does for the ARKit keys; offsets < 0.1 mm are dropped (sparse)."""
    kb = bm.data.shape_keys.key_blocks
    basis = _key_co(bm, kb["Basis"])
    deltas = {n: _key_co(bm, kb[n]) - basis for n in names if n in kb}
    for child in children_meshes(rig):
        if child == bm:
            continue
        path = ClothesService.find_clothes_absolute_path(child)
        if not path:
            continue
        mh = Mhclo(); mh.load(path)
        n = len(child.data.vertices)
        idx = np.zeros((n, 3), dtype=np.int64); w = np.zeros((n, 3))
        for vi, m in mh.verts.items():
            if vi < n:
                idx[vi] = m["verts"]; w[vi] = m["weights"]
        if not child.data.shape_keys:
            child.shape_key_add(name="Basis", from_mix=False)
        cb = _key_co(child, child.data.shape_keys.key_blocks["Basis"])
        added = 0
        for name, D in deltas.items():
            if name in child.data.shape_keys.key_blocks:
                continue
            d = (D[idx] * w[:, :, None]).sum(1)
            d[np.linalg.norm(d, axis=1) < min_shift] = 0.0
            if not d.any():
                continue
            sk = child.shape_key_add(name=name, from_mix=False)
            sk.data.foreach_set("co", (cb + d).ravel()); sk.value = 0.0
            added += 1
        log("  cust -> %-26s %3d morphs" % (child.name, added))


def bone_offsets(rig, bm, names, eps=2e-4):
    """How each cust morph moves the rts_human joints (MPFB rig strategies = joint cubes / vertex means evaluated on the
    morphed basemesh). Returns {morph: {bone: [dx, dy, dz]}} in glTF space (+Y up, +Z forward), metres, >= 0.2 mm."""
    rig_file = [r["path"] for r in AssetService.get_custom_rigs(use_cache=False) if r["name"] == RIG_NAME.split(".", 1)[1]][0]
    kb = bm.data.shape_keys.key_blocks
    for k in kb:
        if k.name in FACE_KEYS or k.name.startswith(CUST):
            k.value = 0.0
    # face_lib's 'rts_face_fix' modelling key (lip seal, < 1 mm) was added after the rig was fitted: mute it while the
    # strategies are evaluated so they reproduce the rest skeleton (the offsets are differences, it does not matter)
    muted = {k.name: k.value for k in kb if k.name == "rts_face_fix"}
    for n in muted:
        kb[n].value = 0.0

    def heads():
        r = Rig.from_json_file_and_basemesh(rig_file, bm)
        return {b: np.array(r.get_best_location_from_strategy(info["head"])) for b, info in r.rig_definition.items()}
    t0 = time.time()
    h0 = heads()
    rest = {b.name: np.array(b.head_local) for b in rig.data.bones}
    err = max(np.abs(h0[b] - rest[b]).max() for b in rest)
    assert err < 1e-4, "rig strategies do not reproduce the rest skeleton (%.2e m)" % err
    out = {}
    for name in names:
        kb[name].value = 1.0
        h = heads()
        kb[name].value = 0.0
        d = {}
        for b in rest:
            v = h[b] - h0[b]
            if np.abs(v).max() >= eps:
                d[b] = [round(float(v[0]), 5), round(float(v[2]), 5), round(float(-v[1]), 5)]   # Blender Z-up -> glTF Y-up
        out[name] = d
    for n, v in muted.items():
        kb[n].value = v
    log("bone offsets for %d morphs in %.1fs (max %d bones moved)" % (len(names), time.time() - t0,
                                                                     max(len(v) for v in out.values())))
    return out


# ------------------------------------------------------------------------------------------------------------------
# Alternate parts
def _asset(sub, style):
    return asset_file(sub, style, style + ".mhclo")


def add_alt_parts(rig, bm, kind):
    """Loads the alternate parts (MPFB mhclo assets, rigged by MPFB weight interpolation) and marks them rts_alt.
    Must run right after build_human (before the eye-socket key fix) so FaceService gives them the same face keys
    as the default parts. Returns [(obj, role, style)]."""
    base = PRESETS[kind].get("tex_kind", kind)
    p = PRESETS[kind]["parts"]
    todo = []
    for sub, role, styles in (("eyebrows", "eyebrows", sorted(os.listdir(asset_file("eyebrows")))),
                              ("eyelashes", "eyelashes", sorted(os.listdir(asset_file("eyelashes")))),
                              ("hair", "hair", HAIR_ALTS[base]), ("hair", "beard", BEARDS[base])):
        default = p.get(role, "").split("/")[0]
        for st in styles:
            if st == default or not os.path.exists(_asset(sub, st)):
                if st != default:
                    log("WARNING: part %s/%s missing (run scripts/hair_gen.py for procedural grooms)" % (sub, st))
                continue
            todo.append((sub, role, st))
    out = []
    for sub, role, st in todo:
        o = HumanService.add_mhclo_asset(_asset(sub, st), bm, asset_type=sub, subdiv_levels=0, material_type="MAKESKIN")
        o["rts_alt"] = 1; o["rts_part"] = role; o["rts_style"] = st
        out.append((o, role, st))
    FaceService.interpolate_targets(bm)            # ARKit + visemes onto the new parts (existing parts are skipped)
    log("alternate parts: %d (%s)" % (len(out), ", ".join("%s/%s" % (r, s) for _, r, s in out)))
    return out


def merge_beard_shadows(rig, kind, alts):
    """Every card beard gets a copy of the stubble shell with the dense 'shadow' texture (beard_shadow_base.png,
    alpha-blended) joined in as a second primitive: same skin weights (MPFB interpolated both from the body), same
    face + cust morphs (Blender's join merges shape keys by name), same hair-colour tint. Without it the skin shows
    between the short cards and the beard reads as blocky patches. Run after the keys are on every part (the mhclo
    correspondence no longer matches a joined mesh)."""
    shell = [o for o, r, st in alts if st == STUBBLE]
    if not shell:
        return 0
    shell = shell[0]
    hf = hair_factor(PRESETS[kind]["hair_rgb"])
    n = 0
    for o, role, st in alts:
        if role != "beard" or st == STUBBLE:
            continue
        cp = shell.copy(); cp.data = shell.data.copy()
        for c in shell.users_collection:
            c.objects.link(cp)
        m = pbr_material("M_%s_beard__%s_shadow" % (kind, st), base=os.path.join(TEX, "beard_shadow_base.png"),
                         rough=0.7, alpha_mode='BLEND', alpha_img_from_base=True, spec=0.25, tint=tuple(hf))
        m.use_backface_culling = True
        set_material(cp, m)
        if o.data.uv_layers.active and cp.data.uv_layers.active:
            cp.data.uv_layers.active.name = o.data.uv_layers.active.name
        keys_o = {k.name for k in o.data.shape_keys.key_blocks} if o.data.shape_keys else set()
        keys_c = {k.name for k in cp.data.shape_keys.key_blocks} if cp.data.shape_keys else set()
        nv = len(o.data.vertices)
        for ob in bpy.context.view_layer.objects:
            ob.select_set(False)
        o.hide_set(False); cp.hide_set(False)
        o.select_set(True); cp.select_set(True)
        bpy.context.view_layer.objects.active = o
        bpy.ops.object.join()
        assert len(o.data.materials) == 2 and len(o.data.vertices) == nv + len(shell.data.vertices), o.name
        got = {k.name for k in o.data.shape_keys.key_blocks}
        assert got == keys_o | keys_c, (o.name, sorted((keys_o | keys_c) - got))
        n += 1
        log("  beard shadow -> %s (%d + %d verts, %d keys)" % (o.name, nv, len(shell.data.vertices), len(got) - 1))
    return n


def srgb_to_linear(c):
    c = np.asarray(c, dtype=np.float64)
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def hair_factor(rgb):
    """baseColorFactor (linear) that turns the neutral strand atlas (strand luminance) into hair_tex.py's colour."""
    return [round(float(x), 4) for x in srgb_to_linear(np.minimum(1.0, np.array(rgb) * 1.5))]


def brow_factor(rgb):
    """Brow card colour for a hair colour: the presets use brow_color = hair_rgb * 0.5 as a (linear) flat colour."""
    return [round(float(x) * 0.5, 4) for x in rgb]


def alt_materials(rig, kind, alts):
    """glTF-friendly materials for the alternate parts. Hair / beards use a neutral (grey) strand texture times a
    baseColorFactor = the hair colour, so one hair-colour parameter drives every style."""
    p = PRESETS[kind]
    base = p.get("tex_kind", kind)
    hf = hair_factor(p["hair_rgb"])
    neutral_atlas = os.path.join(TEX, "hair_strands_neutral_base.png")
    for o, role, st in alts:
        if role in ("eyebrows", "eyelashes"):
            png = asset_file(role, st, st + ".png")
            col = p["brow_color"] if role == "eyebrows" else p["lash_color"]
            set_material(o, pbr_material("M_%s_%s__%s" % (kind, role, st), base=png, rough=0.6, alpha_mode='MASK',
                                         alpha_img_from_base=True, flat_color=col, spec=0.3))
        elif st == STUBBLE:
            m = pbr_material("M_%s_%s__%s" % (kind, role, st), base=os.path.join(TEX, "beard_stubble_base.png"),
                             rough=0.65, alpha_mode='BLEND', alpha_img_from_base=True, spec=0.3, tint=tuple(hf))
            m.use_backface_culling = True
            set_material(o, m)
        else:
            if st.startswith("rts_"):
                tex_, nrm = neutral_atlas, os.path.join(TEX, "hair_strands_normal.png")
            else:
                tex_, nrm = os.path.join(PARTS_TEX, "hair_%s.png" % st), None
            assert os.path.exists(tex_), "missing %s (run scripts/part_tex.py / hair_tex.py neutral)" % tex_
            beard = role == "beard"                   # beards: coarser, less glossy than scalp hair
            m = pbr_material("M_%s_%s__%s" % (kind, role, st), base=tex_, rough=0.58 if beard else 0.45,
                             alpha_mode='MASK', alpha_img_from_base=True, normal=nrm, normal_strength=1.4,
                             spec=0.4 if beard else 0.5, tint=tuple(hf))   # Mix colour (linear) = baseColorFactor
            m.use_backface_culling = False
            set_material(o, m)


def name_parts(rig, kind, alts):
    """Default parts keep their names (<kind>_hair, ...); alternates become <kind>_<role>__<style>. Every part gets
    rts_part / rts_style (+ rts_default) custom properties = glTF node extras."""
    p = PRESETS[kind]["parts"]
    for o in children_meshes(rig):
        if o.get("rts_alt"):
            continue
        role = o.name[len(kind) + 1:]          # finalize_names: <kind>_<role>
        o["rts_part"] = role
        o["rts_default"] = 1
        if role in p:
            o["rts_style"] = p[role].split("/")[0]
    for o, role, st in alts:
        o.name = "%s_%s__%s" % (kind, role, st)
        o.data.name = o.name
        if role in ("hair", "beard") and st.startswith("rts_"):
            set_hair_normals(o, find_part(rig, "_body"))


# ------------------------------------------------------------------------------------------------------------------
# Export specs (consumed by glb_post.py)
def _default_colour(kind):
    """The HAIR_COLOURS entry of the preset's hair colour (nearest one if the preset was re-tuned)."""
    rgb = np.array(PRESETS[kind]["hair_rgb"])
    return min(HAIR_COLOURS, key=lambda nc: float(np.abs(np.array(nc[1]) - rgb).sum()))[0]


def parts_catalogue(rig, kind):
    cat = {"hair": [], "beard": [{"style": "none", "node": None, "default": True}], "eyebrows": [], "eyelashes": []}
    for o in children_meshes(rig):
        role = o.get("rts_part")
        if role in cat:
            cat[role].append({"style": o.get("rts_style"), "node": o.name, "default": bool(o.get("rts_default")),
                              "file": "parts_%s.glb" % kind if o.get("rts_alt") else "base_%s.glb" % kind})
    cat["hair"].append({"style": "none", "node": None, "default": False})
    for v in cat.values():
        v.sort(key=lambda e: (not e["default"], e["style"] == "none", e["style"]))
    return cat


def variant_spec(rig, kind, for_parts):
    """KHR_materials_variants options (glb_post.py) for the base GLB (skin, eyes, hair colour on the default hair and
    brows) or for the parts GLB (hair colour on the alternate hair / beards / brows)."""
    p = PRESETS[kind]
    tk = p.get("tex_kind", kind)
    dcol = _default_colour(kind)
    V = []
    if not for_parts:
        for tone, mix, _ in SKIN_TONES[tk]:
            V.append({"name": "skin:" + tone, "materials": {"M_%s_skin" % kind: {} if mix is None else
                      {"baseColorTexture": os.path.join(TEX, "%s_skin_%s_base.jpg" % (tk, tone))}}})
        for tone, f in SKIN_TINTS:
            V.append({"name": "skin:" + tone, "materials": {"M_%s_skin" % kind: {"baseColorFactor": list(f) + [1.0]}}})
        for c in EYE_COLOURS:
            V.append({"name": "eyes:" + c, "materials": {"M_%s_eye" % kind: {} if c == p["eye_color"] else
                      {"baseColorTexture": os.path.join(PARTS_TEX, "eye_%s.jpg" % c)}}})
    dhair = p["parts"]["hair"].split("/")[0]
    neutral_default = os.path.join(TEX, "hair_strands_neutral_base.png") if dhair.startswith("rts_") else \
        os.path.join(PARTS_TEX, "hair_%s.png" % dhair)
    for cname, rgb in HAIR_COLOURS:
        mats = {}
        for o in children_meshes(rig):
            if bool(o.get("rts_alt")) != for_parts or not o.data.materials:
                continue
            role = o.get("rts_part")
            if role not in ("hair", "beard", "eyebrows"):
                continue
            if cname == dcol:
                ov = {}
            elif role in ("hair", "beard"):
                ov = {"baseColorFactor": hair_factor(rgb) + [1.0]}
                if not for_parts:                      # the default hair ships the coloured atlas: swap to neutral
                    ov["baseColorTexture"] = neutral_default
            else:
                ov = {"baseColorFactor": brow_factor(rgb) + [1.0]}
            for mat in o.data.materials:               # card beards: cards + their shadow shell
                # scalp caps (hair_lib.join_caps, '<hair material>_cap'): own neutral texture, recoloured by the factor
                mats[mat.name] = {a: b for a, b in ov.items() if a != "baseColorTexture"} if mat.name.endswith("_cap") else ov
        V.append({"name": "hair:" + cname, "materials": mats})
    return V


def extras_spec(rig, kind, cstats, offsets):
    tk = PRESETS[kind].get("tex_kind", kind)
    sl = []
    for sid, grp, lab, neg, pos, rnd in sliders_for(kind):
        nl, pl = [x.strip() for x in lab.split("/")]
        sl.append({"id": sid, "group": grp, "label": sid.replace("_", " ").capitalize(), "neg_label": nl,
                   "pos_label": pl, "neg": CUST + sid + "_neg" if neg is not None else None,
                   "pos": CUST + sid + "_pos", "rand": rnd,
                   "source": {"neg": neg, "pos": pos}, "preset_modifier": PRESET_MOD.get(sid)})
    return {
        "version": 1, "kind": kind, "base_kind": tk, "morph_prefix": CUST,
        "sliders": sl,
        "variants": {"skin": [t[0] for t in SKIN_TONES[tk]] + [t for t, _ in SKIN_TINTS], "eyes": EYE_COLOURS,
                     "hair": [n for n, _ in HAIR_COLOURS]},
        "variant_tints": [t for t, _ in SKIN_TINTS],
        "variant_defaults": {"skin": "fair", "eyes": PRESETS[kind]["eye_color"], "hair": _default_colour(kind)},
        "hair_colours": {n: {"srgb": list(c), "factor": hair_factor(c), "brow_factor": brow_factor(c)} for n, c in HAIR_COLOURS},
        "parts": parts_catalogue(rig, kind),
        "bone_offsets": offsets,
        "morph_stats": cstats,
        "notes": ["slider s in [-1,1]: weight(neg morph) = max(0,-s), weight(pos morph) = max(0,s); the values are "
                  "offsets from this base preset; |s| <= 1 stays within MakeHuman's authored range",
                  "cust_* morphs are additive with the ARKit / viseme morphs (same mesh, same vertex order)",
                  "variants: one KHR_materials_variants variant per '<category>:<option>', apply one per category",
                  "parts: alternates live in parts_<kind>.glb, skinned to the same rts_human joints (bind by joint "
                  "name); they carry the same morph names, drive them with the same weights",
                  "bone_offsets: glTF-space joint head deltas (m) at morph weight 1; to refit, add sum(w * delta) to "
                  "each joint's rest world position (local translation = parent rest rotation^-1 * (d_child - "
                  "d_parent)) and recompute the inverse bind matrices at rest; optional for moderate shapes"],
    }


CARD_PARTS = ("hair", "beard", "eyebrows", "eyelashes")
CARD_MESH_RX = r"_(hair|beard|eyebrows|eyelashes)(__.*)?$"


def sparsify_card_keys(obj, eps=3e-4):
    """Hair / beard / brow / lash cards: zero per-vertex morph offsets below eps (0.3 mm, invisible on cards) so the
    glTF sparse accessors stay small; keys left empty are removed. Returns (keys removed, offsets zeroed)."""
    if not obj.data.shape_keys:
        return 0, 0
    kb = obj.data.shape_keys.key_blocks
    base = _key_co(obj, kb["Basis"])
    removed = zeroed = 0
    for k in list(kb)[1:]:
        d = _key_co(obj, k) - base
        small = np.linalg.norm(d, axis=1) < eps
        nz = np.abs(d).max(1) > 0
        zeroed += int((small & nz).sum())
        d[small] = 0.0
        if not d.any():
            obj.shape_key_remove(k); removed += 1
            continue
        k.data.foreach_set("co", (base + d).ravel())
    if len(obj.data.shape_keys.key_blocks) == 1:
        obj.shape_key_clear()
    return removed, zeroed


def ground_export(rig, kind):
    """Engine export only (after the live .blend is saved): put the soles on the ground. MPFB grounds the macro body,
    so detail targets that shorten the legs (proportion variants: male_stocky) leave the feet floating. Shifts every
    mesh (vertices + all shape keys) and every bone by the same -z (the ground 'root' joint goes to z = 0)."""
    body = find_part(rig, "_body")
    kb = body.data.shape_keys.key_blocks if body.data.shape_keys else None
    co = _key_co(body, kb["Basis"]) if kb else np.array([v.co[:] for v in body.data.vertices])
    z0 = float(co[:, 2].min())
    if abs(z0) < 1e-4:
        return 0.0
    for o in children_meshes(rig):
        n = len(o.data.vertices)
        a = np.empty(n * 3); o.data.vertices.foreach_get("co", a); a = a.reshape(-1, 3); a[:, 2] -= z0
        o.data.vertices.foreach_set("co", a.ravel())
        if o.data.shape_keys:
            for k in o.data.shape_keys.key_blocks:
                b = _key_co(o, k); b[:, 2] -= z0; k.data.foreach_set("co", b.ravel())
        o.data.update()
    bpy.context.view_layer.objects.active = rig
    for ob in bpy.context.selected_objects:
        ob.select_set(False)
    rig.select_set(True)
    bpy.ops.object.mode_set(mode='EDIT')
    for eb in rig.data.edit_bones:
        dz = z0 if eb.name != "root" else eb.head.z
        eb.head.z -= dz; eb.tail.z -= dz
    bpy.ops.object.mode_set(mode='OBJECT')
    log("%s grounded: soles were %.1f mm above the floor" % (kind, z0 * 1000))
    return z0
